### ISSUE TITLE
App crashes / disconnect

### ISSUE THREAD

**Issue by lucasnordic** [DIT112-V21/group-10#43]
As a user, I want the car to throttle down until it stops when I'm not in control of the carso that it does not crash or run into obstacles.
---
Acceptance criteria: 
- [ ] If connection is lost to car; car should throttle down until it stops!
- [ ] If user leaves the screens related to controlling the car (the manual and autopilot pages); Car should throttle down until it stops!

**Comment by platisd** [comment]
> I want the GeoBot to break

Why do you want GeoBot to _break_? :fearful:

**Comment by lucasnordic** [comment]
> > I want the GeoBot to break
> 
> Why do you want GeoBot to _break_? 😨

Someone has to fight back against the technological singularity!! Erhm, I agree that the wording is not great :')
