### ISSUE TITLE
All sensor output to UI

### ISSUE THREAD

**Issue by lucasnordic** [DIT112-V21/group-10#44]
As a gamer I want the car to receive all the available sensor information from TANK so that I can get more data for my competitive skills.

Acceptance Criteria: The car outputs its sensor data to a page on the UI.

- [ ] Odometer data (from DistanceCar)
* getDistance
* getSpeed

- [ ] InfraredAnalogSensor data
* getMedianDistance
* getDistance, for all 4 sensors

- [ ] HeadingSensor (Gyroscope)
* getHeading

**Comment by HIMANKMEATTLE** [comment]
The screen has speed slider, score and timer information.

**Comment by himankmeattle** [comment]
The screen has speed slider, score and timer information.
