### ISSUE TITLE
Improve/update the UI

### ISSUE THREAD

**Issue by Irina0904** [DIT112-V21/group-10#54]
### Acceptance criteria:

- [x] Update name “GeoBot” - Lucas
- [x] Fix the colour scheme of the UI, make the colors less vibrant and more friendly for the eye - Hannah
- [ ] Include bottom navigation for the UI to make sure the user doesn’t have to go back to the main menu every time they want to switch activities - Irina
- [x]  The help screen has been updated to cover the sprint change.
- [ ] The sky in the video feed is blue and not yellow while running the app.

**Comment by himankmeattle** [comment]
done
