### ISSUE TITLE
Add car Information to the manual Screen

### ISSUE THREAD

**Issue by Spidergirl93** [DIT112-V21/group-10#65]
The car information (Speed, distance from obstacles, warnings to user) are printed in the serial of the emulator. 
The user must be able to get these information from the Manual screen of their android device.

**Comment by lucasnordic** [comment]
Himank is working on this in #44. Though, maybe we should be more specific in that issue, and say that the user should have access to this information in the manual screen? 💭

I like the warning part though. Maybe a red alert message should appear like, "Hostile bot spotted!"

**Comment by Spidergirl93** [comment]
> Himank is working on this in #44. Though, maybe we should be more specific in that issue, and say that the user should have access to this information in the manual screen? 💭
> 
> I like the warning part though. Maybe a red alert message should appear like, "Hostile bot spotted!"

Yeah You are right, we can discuss this in the meeting to decide wat to display to the user while running the program. It's only the Idea right now.
