### ISSUE TITLE
Change Broker/Host + Port

### ISSUE THREAD

**Issue by lucasnordic** [DIT112-V21/group-10#98]
As a user I would like to be able to change Broker/server so that I have more options of which broker I would like to use.

Acceptance criteria:
- [x] The user should be able to change Broker in the Application
- [ ] The user should be able to change Broker on the Smartcar as well, so that no messing around in the code is necessary.

**Comment by lucasnordic** [comment]
Reopening since it only solved the first point

**Comment by himankmeattle** [comment]
managed to fix partially and the team decided to close the issue. Future developers can dwell into it further.
